### ISSUE TITLE
Publish distro version of EthQL in npm registry

### ISSUE THREAD

**Issue by raulk** [ConsenSys/ethql#112]
We have secured the `@ethql` org in npm, so now it's time to ship some stuff there!

Once we complete the changes requested in #107, we'll end up publishing a module structure as follows:

```
@ethql
  |___ base
  |___ core-plugin
  |___ erc20-plugin
  |___ ens-plugin
  |___ erc721-plugin
  |___ ...
```

Additionally, we'll publish an `@ethql/distro` package with a standalone server that brings together the base and all the plugins maintained by the EthQL team.... This looks like what we have now (before #107 completes) ;-)

So I'm going to go ahead and publish the current state under the `@ethql/distro` package!

**Comment by kshinn** [comment]
This was finished. There is some slight nomenclature differences. Rather than `distro` it was published as `server` which might make more semantic sense. Open to renaming if it works better.
