### ISSUE TITLE
Explicit test coverage for scalar types

### ISSUE THREAD

**Issue by raulk** [ConsenSys/ethql#72]
Follows on from #70. Existing tests don't use GraphQL variables and hence only test the `parseLiteral` variant of the parsing. 

The idea is to make scalar testing explicit by testing all parsing variants in a `scalars.test.ts` suite.

See #70 for more context.

**Comment by raulk** [comment]
@pcardune @akhila-raju would any of you be up for taking this one?

**Comment by akhila-raju** [comment]
Got this one :)
