### ISSUE TITLE
Query documentation

### ISSUE THREAD

**Issue by rokcarl** [ConsenSys/ethql#75]
I'd love to use ethql for a project I'm working on where I would be analyzing a specific token. Except for a couple examples in the readme, I don't see any documentation on how to use this tool for querying Ethereum. What's the best way to approach this?

**Comment by raulk** [comment]
Hey @rokcarl, currently you can access our test endpoint at:

http://ethql-lb-979715030.eu-west-3.elb.amazonaws.com/graphql

It's running the GraphiQL tool which has code completion, and schema documentation on the sidebar panel. Maybe have a look if that helps for now.

@akhila-raju will also be working on a **Query handbook** in the next days (issue to follow up shortly).

**Comment by rokcarl** [comment]
Nice, thank you!

And please link to the issue so I'll be able to check its progress.

**Comment by akhila-raju** [comment]
https://github.com/ConsenSys/ethql/issues/76 :)
