### ISSUE TITLE
[Upgrade] Replace Express-GraphQL with Apollo Server 2?

### ISSUE THREAD

**Issue by rej156** [ConsenSys/ethql#83]
Lower the load on Infura too for https://ethql-alpha.infura.io/graphql
https://blog.apollographql.com/announcing-apollo-server-2-2b69fb4702ce?gi=c9f8d90c7e53

**Comment by raulk** [comment]
@jonathanBuhler – could you do a short spike here, and outline the changes necessary to migrate from express-graphql to Apollo Server 2?

**Comment by rej156** [comment]
https://www.apollographql.com/docs/apollo-server/v2/migration-two-dot.html

**Comment by raulk** [comment]
Done in #91.
